13 improve description
koindx/v2-core pull request #14
Opened 2023-08-27 17:47 UTC by ederaleng

Updated the descriptions of each pool method

2023-08-28 22:23 UTC, vonlooten requested changes
Looks good, I only had some questions regarding the descriptions

2023-08-28 22:23 UTC, vonlooten commented on assembly/proto/core.proto
> +// @description get reserver of a pool
@ederaleng "get reserves of a pool" ?

2023-08-28 22:23 UTC, vonlooten commented on assembly/proto/core.proto
> +// @description Sets `amount` as the allowance of `spender` over the caller's tokens.
@ederaleng Sets `value` as the allowance of `spender` over the caller's tokens. 

// because parameter name is value

2023-08-29 13:31 UTC, ederaleng commented on assembly/proto/core.proto
> +// @description get reserver of a pool
This method returns the token reserves within the pool

2023-08-29 13:35 UTC, ederaleng commented on assembly/proto/core.proto
> +// @description Sets `amount` as the allowance of `spender` over the caller's tokens.
I just changed amount to value

2023-08-29 15:56 UTC, vonlooten approved these changes

2023-08-29 15:56 UTC, merged